-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."ActivationByEmail"
(
    "UserId" integer NOT NULL,
    "ActivationCode" character varying(60) NOT NULL,
    "Confirmed" boolean NOT NULL,
    PRIMARY KEY ("UserId")
);

CREATE TABLE public."ActivationByStaff"
(
    "UserId" integer NOT NULL,
    "StaffId" integer NOT NULL,
    "Confirmed" boolean NOT NULL,
    PRIMARY KEY ("UserId")
);

CREATE TABLE public."Candidates"
(
    "UserId" integer NOT NULL,
    "FistName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "NationalId" character varying(11) NOT NULL,
    "YearOfBirth" date NOT NULL,
    PRIMARY KEY ("UserId")
);

CREATE TABLE public."Employers"
(
    "UserId" integer NOT NULL,
    "CompanyName" character varying(50) NOT NULL,
    "Website" character varying(50) NOT NULL,
    "Phone" character varying(14) NOT NULL,
    PRIMARY KEY ("UserId")
);

CREATE TABLE public."JobTitles"
(
    "Id" integer NOT NULL,
    "JobTitle" character varying(50) NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE public."Staffs"
(
    "UserId" integer NOT NULL,
    "FirstName" character varying(50) NOT NULL,
    "LastName" character varying(50) NOT NULL,
    "NationalId" character varying(11) NOT NULL,
    "YearOfBirth" date NOT NULL,
    PRIMARY KEY ("UserId")
);

CREATE TABLE public."Users"
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 2147483647 CACHE 1 ),
    "Email" character varying(50) NOT NULL,
    "Password" character varying(20) NOT NULL,
    PRIMARY KEY ("Id")
);

ALTER TABLE public."ActivationByEmail"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Candidates" ("UserId")
    NOT VALID;


ALTER TABLE public."ActivationByEmail"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Employers" ("UserId")
    NOT VALID;


ALTER TABLE public."ActivationByStaff"
    ADD FOREIGN KEY ("StaffId")
    REFERENCES public."Staffs" ("UserId")
    NOT VALID;


ALTER TABLE public."ActivationByStaff"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Employers" ("UserId")
    NOT VALID;


ALTER TABLE public."Candidates"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."Employers"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("Id")
    NOT VALID;


ALTER TABLE public."Staffs"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("Id")
    NOT VALID;

END;