-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.activation_by_email
(
    user_id integer NOT NULL,
    activation_code character varying(60) NOT NULL,
    confirmed boolean NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.activation_by_staff
(
    user_id integer NOT NULL,
    staff_id integer NOT NULL,
    confirmed boolean NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.candidates
(
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    national_id character varying(11) NOT NULL,
    year_of_birth date NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    company_name character varying(50) NOT NULL,
    website character varying(50) NOT NULL,
    phone character varying(14) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.job_titles
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 2147483647 CACHE 1 ),
    job_title character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.staffs
(
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    national_id character varying(11) NOT NULL,
    year_of_birth date NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(50) NOT NULL,
    password character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.activation_by_email
    ADD FOREIGN KEY (user_id)
    REFERENCES public.candidates (user_id)
    NOT VALID;


ALTER TABLE public.activation_by_email
    ADD FOREIGN KEY (user_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.activation_by_staff
    ADD FOREIGN KEY (staff_id)
    REFERENCES public.staffs (user_id)
    NOT VALID;


ALTER TABLE public.activation_by_staff
    ADD FOREIGN KEY (user_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.candidates
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.staffs
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;

END;